### ISSUE TITLE
Exporter des métadonnées supplémentaires

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archifiltre-docs#1471]
### EPIC

#19

### AFTER

#1452

### Contexte

Il est maintenant possible d'afficher des métadonnées supplémentaires dans Archifiltre-Docs et de les visualiser dans l'interface.

### Définition du(des) problème(s)

Ces métadonnées supplémentaires doivent pouvoir être également exportées dans les différents exports possibles à partir d'Af-Docs

### Solution

ETQ utilisateur d'Af-Docs
JVP exporter les métadonnées supplémentaires que j'aurais insérées dans Af dans:
- les fichiers de récolement CSV, XLS, CSV hierarchisés, CSV avec empreintes en affichant dans cet export 1 colonne par métadonnée supplémentaire
- l'export Resip
AD pouvoir les utiliser également hors de l'outil.

### Critères d'acceptance

Pour l'export Resip, voici la liste des métadonnées SEDA qu'il faut proposer:
- `<CustodialHistory>`: cette balise est déjà renseignée dans l'export Resip, si le champ contient déjà des éléments, il faudra les ajouter dans ce champ
- `<DescriptionLevel>`
- `<Title>`
- `<Tags>`: cette balise est déjà renseignée dans l'export Resip, si le champ contient déjà des éléments, il faudra les ajouter dans ce champ
- `<ArchivalAgencyArchiveUnitIdentifier>`

### TODO

- [X] Configurer les métadonnées
- [X] Exporter les métadonnées dans RESIP
  - [X] Exporter le Custodial History
  - [X] Exporter les tags
  - [X] Exporter le Title
  - [X] Exporter le ArchivalAgencyArchiveUnitIdentifier
  - [ ] Exporter le DescriptionLevel => Les valeur du champ sont limités, ça demande un peu plus de réflexion métier
- [X] Enregistrer les métadonnées dans le fichier de sauvegarde
- [x] Charger les métadonnées depuis le fichier de sauvegarde
- [x] Réinitialiser les métadonnées lorsqu'on clique sur fermer
- [x] Configuration de la colonne du chemin
- [x] Cocher par défaut les colonnes à importer 
- [x] Corriger les chemins windows pour qu'ils correspondent aux chemin linux
- [ ] Finaliser les textes/design
- [ ] Finaliser les tests unitaires
- [x] Pouvoir revenir en arrière sur la fenêtre de dépôt de fichier
- [x] Ajouter les métadonnées dans l'export Excel
- [x] Ajouter les métadonnées dans l'export CSV
- [x] Pouvoir charger un fichier métadonnées Excel
- [ ] Pouvoir charger un fichier métadonnées JSON => A détailler fonctionnellement
- [ ] Ajouter les tests e2e

### Les tests e2e doivent-ils passer ?

- [ ] e2e
